config/routes.rb
Rails.application.routes.draw do
  
  root 'welcomes#index'
  resources :contacts#, only: [:new, :create]
  resources :welcomes#, only: [:new, :create, :index]
  get 'imprint' => 'static_pages#imprint'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :message, presence: true
  validates :email, presence: true
  validates :email, email: true
end

app/models/email_validator.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "Bitte tragen Sie eine gültige Email ein")
    end
  end
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  #def index
   # @contacts = Contact.all
  #end

  # GET /contacts/1
  # GET /contacts/1.json
  #def show
  #end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  #def edit
  #end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: 'Vielen Dank für die Nachricht.' }
        #format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        #format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end
=begin
  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
=end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def imprint
    @contact = Contact.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  # main page
  def index
    @welcome = Welcome.new
    @contact = Contact.new
  end


  # POST /welcomes
  # POST /welcomes.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to root_path, notice: 'Vielen Dank für die Nachricht.' }
        #format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render root_path}
        #format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:welcome).permit(:name, :email, :message)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
    def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
  
  
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h4>Bitte schauen Sie sich folgende Punkte nochmals an: </h4>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name , for:"name" , class:"black nj"%>
    <%= f.text_field :name , class:"form-control", id:"name", type:"text", placeholder:"Name" , required: true %>
  </div>

  <div class="form-group">
    <%= f.label :email , for:"email", class:"black nj"%>
    <%= f.text_field :email, class:"form-control", id:"email", type:"email", placeholder:"Email" %>
  </div>

  <div class="form-group">
    <%= f.label :nachricht , for:"msg", class:"black nj"%>
    <%= f.text_area :message, class:"form-control", id:"msg", type:"text", placeholder:"Nachricht", rows:"9", required: true %>
  </div>

<div class="modal-footer">
  <div class="actions">
    <%= f.submit "Senden", class:"btn btn-success" %>
      </div>

  </div>

        

<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.haml
%section#contact
  .container
    .row
      .col-md-12.col-xs-12
        %header
          <h1 class="page-header">Kontakt</h1>
        = render 'form', contact: @contact

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="de">
  <head>
    
    <title>Limo | Gutschein-Journal</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
  <!-- nav -->
    <%= render 'shared/nav' %>
    <%= render 'shared/flash' %>
    <%= yield %>
 <!-- footer -->
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert flash-msg fade in">
    <i data-dismiss="alert" class="fa fa-close thin"></i>
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.haml
%footer#footer
	.container-fluid
		.row
			.col-md-8.col-md-offset-2.col-xs-12
				.row
					.col-md-6
						Copyright 
						&copy; 2017
						= link_to 'Limo - Gutschein Journal', root_path, class:"foo-link"
					.col-md-6
						%ul.list-inline.right-list
							%li.foo
								%a{'data-target' => "#myModal", "data-toggle"=>"modal", :class=>"foo-link"}
									Kontakt
							%li.foo
								=link_to 'Impressum', imprint_path, class:"foo-link"
							%li.foo
								|
								&nbsp;
								&nbsp;
								&nbsp;
								Folge uns auf Facebook: 
								&nbsp;
								%a.foo-link.fb{:href=>"https://www.facebook.com/limojournal/", :target=>"_blank"}
									<i class="fa fa-facebook-square"></i>

= render 'shared/mo'
							

app/views/shared/_mo.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title black" id="myModal">Kontakt</h4>
      </div>
      <div class="modal-body">

      <%#= render 'welcomes/form' %>
      <%= render 'contacts/form' %>
      
      </div>

    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default limo-nav">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button><a class="navbar-brand" href="/">
        LIMO <span class="br-sm">- Gutschein Journal</span>
      <%#= image_tag "logo-limo_nav2.png" , class:"logo"%></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#video">Video</a></li>
        <li><a class="foo-link" data-target="#myModal" data-toggle="modal">
Kontakt
</a></li>
        <li><%= link_to "Impressum", imprint_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/static_pages/imprint.html.haml
#impressum.static
  .container
    .row
      .col-md-12
        %header
          %h1.page-header.skl
            Impressum
    .row
      .col-md-12
        %p
          Die Webseite 
          =link_to 'www.limo-journal.de', root_path
          ist ein Produkt von: 
        %address
          <em title="author" class="text-bold">AMV Ardland Medien & Vertriebs GmbH</em><br><br><span class="text-bold"> Amtsgericht Osnabrück Handelsregister-Nummer HRB 211375<br></span><span>Steuernummer: 66/200/00669</span>
        <span>Anton Storch Straße 21 <br>49080 Osnabrück <br /><br /> Telefon: 0541 – 506 49 16 <br> Handy: 0171 – 529 49 16<br> Fax: 0541 – 998 99 056</span>
        %address{:type=>"mail"}
          Email: 
          =mail_to('info@MrScheck.de', name= "info@MrScheck.de")
        %a{:href=>"htttp://www.MrScheck.de", :target=>"_blank"}
          www.MrScheck.de
 

app/views/welcomes/_form.html.erb
<%= form_for(@welcome) do |f| %>
  <% if @welcome.errors.any? %>
    <div id="error_explanation">
      <h4>Bitte schauen Sie sich folgende Punkte nochmals an: </h4>

      <ul>
      <% @welcome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name , for:"name"%>
    <%= f.text_field :name , class:"form-control", id:"name", type:"text", placeholder:"Name" %>
  </div>

  <div class="form-group">
    <%= f.label :email , for:"email"%>
    <%= f.text_field :email, class:"form-control", id:"email", type:"email", placeholder:"Email" %>
  </div>

  <div class="form-group">
    <%= f.label :nachricht , for:"msg"%>
    <%= f.text_area :message, class:"form-control", id:"msg", type:"text", placeholder:"Nachricht", rows:"9"%>
  </div>

  <div class="actions">
    <%= f.submit "Senden", class:"btn btn-success" %>
  </div>
<% end %>

app/views/welcomes/_st.html.haml
.container-fluid
  .row
    .col-md-8.col-md-offset-2.lik
      .row
        .col-md-3.col-xs-6.zener
          %ul.markt_features_list
            %li.list_element
              .sig
                %i.fa.fa-certificate
            %li.list_element  
              %span.nu
                55
              %span.nv
                Kooperationspartner
              %p
                Wir arbeiten mit verschiedenen Kooperationspartnern. 
                -#%br
                  = link_to 'Kontaktieren Sie uns', new_contact_path, class:"white"
        
        .col-md-3.col-xs-6.zener
          %ul.markt_features_list
            %li.list_element
              .sig
                %i.fa.fa-heart-o
            %li.list_element
              %span.nu
                50
              %span.nv
                Gutscheine
              %p
                Wir setzten auf Mehrwerte. Das Limo Journal beinhaltet attraktive u.a. 2für1 Gutscheine.
        
        .col-md-3.col-xs-6.zener
          %ul.markt_features_list
            %li.list_element
              .sig
                %i.fa.fa-globe
            %li.list_element
              %span.nu
                2.0
              %span.nv
                Print & Online
              %p
                Das Limo-Journal ist online interaktiv - für noch mehr Reichweite.

        .col-md-3.col-xs-6.zener
          %ul.markt_features_list
            %li.list_element
              .sig
                %i.fa.fa-envelope-open-o
            %li.list_element
              %span.nu
                100%
              %span.nv
                Verteilung
              %p
                Das Limo-Journal wird zu 100% verteilt - ohne Streuverluste - für noch mehr Reichweite.

app/views/welcomes/index.html.haml
%article#limo-main_article
  %section.shine
    .container-fluid
      .rows
        -#.col-md-10.col-md-offset-1.col-xs-12.col-lg-10.col-lg-offset-1
        .col-md-8.col-md-offset-2.col-xs-12#lim
          %header
            %h1
              %span.li
                = image_tag 'logo-limo_250.jpg', class:"lm-lg"
      .row
        .col-md-8.col-md-offset-2.col-xs-12#l
          .fro
            <iframe width="100%" height="585px" src="https://www.yumpu.com/de/embed/view/3CyJvVp5QMhTtLXD" frameborder="0" allowfullscreen="true"  allowtransparency="true"></iframe>
          %hr
  %section
    .container-fluid
      .rows
        -#.col-md-10.col-md-offset-1.col-xs-12.col-lg-10.col-lg-offset-1
        .col-md-8.col-md-offset-2.col-xs-12
          %header
            %h2.seli
              Limo Journal
              %span.thin
                \-
              %span.col
                Mediadaten
            %p.info
              Die Mediadaten vom Limo-Journal.
          .img-frame
            //= image_tag 'logo-limo_250.jpg', class:"logo-welcome"
          .data-frame
            <iframe width="100%" height="701px" src="https://www.yumpu.com/de/embed/view/vmG1N6HrlYVJyS59" frameborder="0" allowfullscreen="true"  allowtransparency="true" info="false" class="yumpu-video"></iframe>

  %section#limo-main_info.shine
    = render 'st'

  %section#welcome-media_daten
    .container-fluid#video
      .row
        .col-md-8.col-md-offset-2.col-xs-12
          %header
            %h2.seli
              Limo Journal
              %span.thin
                \-
              %span.col
                Video
            %p.info
              Ein Einblick in das Limo-Journal.
          .data
            <iframe src="//yumpu.com/en/video/view/0eebf05918185344?color=%23FFFFFF" width="720" height="405" frameborder="0" allowfullscreen="true"></iframe>
          .btn-c.text-center
            <!--iframe src="https://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.limo-journal.de&width=350&layout=standard&action=like&size=large&show_faces=true&share=true&height=80&appId" width="350" height="90" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe-->
        